# deployments/react-app-deployment-v1.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-v1
spec:
  replicas: 1  # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: react-app
      version: v1
  template:
    metadata:
      labels:
        app: react-app
        version: v1
    spec:
      containers:
      - name: react-app
        image: my-registry/my-react-app:v1  # Docker image for v1
        ports:
        - containerPort: 80
